### ISSUE TITLE
Bug: Doesn't work on Linux

### ISSUE THREAD

**Issue by TheCheddarCheese** [Friends-of-Monika/mas-autostart#9]
### What happened?

I enabled the option in-game but I still have to start it manually when I boot my computer

OS: Linux Mint 21

### Submod version

1.1.9

### Monika After Story version

0.12.15

### Unstable

No

### Code of Conduct and Contribution Guidelines

- [X] I agree to follow this project's Code of Conduct and Contribution Guidelines

**Comment by dreamscached** [comment]
Can you type this in a terminal and show me what it prints out?
```shell
ls ~/.config/autostart
cat ~/.config/autostart/Monika After Story.desktop
```

Additionally, can you give me the `submod_log.log`?

**Comment by TheCheddarCheese** [comment]
okay i think i got the issue, it doesn't work if the folder has spaces, you'd have to put it in airquotes for it to work

**Comment by TheCheddarCheese** [comment]
yeah i modified the .desktop and now it works
